Initial commit
kirillbowkin/ip-distinct-counter pull request #1
Opened 2022-10-01 13:11 UTC by kirillbowkin

2022-10-07 19:57 UTC, LennyKhusaenov requested changes
Есть замечания в стилистическом плане и в плане проектирования. Но в целом работа хорошая) удачи

2022-10-07 19:57 UTC, LennyKhusaenov commented on .idea/.gitignore
> +# Default ignored files
Папки .idea точно не должно быть в репозитории, папки target тоже. твой гитигнор, кажется не отработал :)

2022-10-07 19:57 UTC, LennyKhusaenov commented on ip.txt
> +145.67.23.4
такие файлы должны лежать в папке resources

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/command/IpCountCommand.java
> +        System.out.printf("Using %s\n", ipCounter.toString());
Используй логгер для предоставления информации пользователю. Никогда и нигде не стоит использовать стандартный вывод (для ошибок тоже)

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/command/IpCountCommand.java
> +        if("naive".equals(mode)) {
можно вынести в константы повторяющиеся литералы

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/command/IpCountCommand.java
> +        if("naive".equals(mode)) {
если ты хочешь по умолчанию вернуть наивную реализацию, тогда может стоит переписать? и в принципе параметр "naive" убрать?)
```
if("hll".equals(mode)) {
   return IpCounters.hll();
}
return IpCounters.naive()```

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/ipCounter/HllIpCounter.java
> +    private final HLL hll;
я не против библиотек и круто, что ты о них знаешь или нашел) но можно было и стандартным массивом или 2 битсетами обойтись:)

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/ipCounter/HllIpCounter.java
> +public class HllIpCounter implements IpCounter {
этот класс нарушает single responsibility principle. Он и читает из файла, и считает IP адреса. По хорошему разделить эти обязанности

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/ipCounter/HllIpCounter.java
> +public class HllIpCounter implements IpCounter {
попутно еще конвертит айпишник в байты..)

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/ipCounter/HllIpCounter.java
> +        try (Stream<String> s = Files.lines(path)) {
Лайк за nio 👍

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/ipCounter/IpCounter.java
> +    int count(Path path);
по сути ведется подсчет уникальных айпишников, ни из имени метода, ни из имени класса это непонятно

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/command/IpCountCommand.java
> +    @Option(names = {"-m", "--mode"}, description = {"naive, hll"})
лайк за однозначные опции 👍

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/ipCounter/NaiveIpCounter.java
> +public class NaiveIpCounter implements IpCounter {
та же тема про единую ответственность

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/ipCounter/NaiveIpCounter.java
> +public class NaiveIpCounter implements IpCounter {
еще лучше бы линию отступить перед `@Override`

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/test/java/kirill/bowkin/AppTest.java
> +        assertTrue( true );
оч полезный тест)))

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/ipCounter/IpCounters.java
> +        return new HllIpCounter(new HLL(14, 5), Hashing.murmur3_128());
ради этой одной строчки мы привезли в проект гугловую либу?) я опять же не против, но в реале может оказаться, что джарник быстро потолстеет)

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/test/java/kirill/bowkin/ipCounter/HllIpCounterTest.java
> +}
нет пустой линии в конце
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/main/java/kirill/bowkin/App.java
> +    public static void main(String[] args) {
где-то ты пишешь впритык к названию класса, где-то нет

2022-10-07 19:57 UTC, LennyKhusaenov commented on src/test/java/kirill/bowkin/ipCounter/HllIpCounterTest.java
> +        int count = hllIpCounter.count(path);
btw: можно как вариант сделать лист со значениями (нам наверн и не нужно 80 строк, нет концептуальной разницы между 10 и 80) и писать его в `@TempDir`, https://www.baeldung.com/junit-5-temporary-directory, тогда можно будет выкинуть его из репы) НО так тоже можно в целом)

2022-10-11 23:03 UTC, kirillbowkin commented
Не знаю на сколько удачно получилось тут все распилить) [89b2deb](https://github.com/kirillbowkin/ip-distinct-counter/pull/1/commits/89b2debe085b796a82c74a5fa8bb6ae1caf5c5b9)

2022-11-07 11:28 UTC, merged